#! /bin/sh

xbindkeys
sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12 

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# For Java-based applications
wmname LG3D

# Run applications on startup
# google-chrome-stable &
# slack &
# spotify &
# discord &
# steam &

# bspc rule -a google-chrome desktop='^1'
# bspc rule -a slack desktop='^6'
# bspc rule -a spotify desktop='^7'
# bspc rule -a discord desktop='^8'
# bspc rule -a Steam desktop='^9'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh
